### ISSUE TITLE
Can't work on Django==1.8.6

### ISSUE THREAD

**Issue by haoglehaogle** [ericflo/django-pagination#50]
Hello,
I get error information after installed on django 1.8.6:
(I sure that setting.py is right, and can import TOKEN_BLOCK from command line )

'pagination_tags' is not a valid tag library: ImportError raised loading pagination.templatetags.pagination_tags: cannot import name TOKEN_BLOCK.

**Comment by MastaChimp** [comment]
I have the same error

**Comment by zanpen2000** [comment]
I have the same error 2

**Comment by erickpeirson** [comment]
This is fixed here: https://github.com/erickpeirson/django-pagination

```shell
pip install -U git+https://github.com/erickpeirson/django-pagination@master
```
